name: Build

on: push

jobs:
  # Stable branch
  # build-latest:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :latest
  #       if: success()
  #       run: make build
  #
  # build-ubuntu:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :ubuntu
  #       if: success()
  #       run: make build-ubuntu
  #
  # build-ubuntu-win32:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :ubuntu-win32
  #       if: success()
  #       run: make build-ubuntu-win32
  #
  # build-nvidia:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :nvidia
  #       if: success()
  #       run: make build-nvidia
  #
  # build-nvidia-win32:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :nvidia-win32
  #       if: success()
  #       run: make build-nvidia-win32
  #
  #
  # build-ubuntu-py38:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :ubuntu-py38
  #       if: success()
  #       run: make build-ubuntu-py38
  #
  # build-ubuntu-win32-py38:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :ubuntu-win32-py38
  #       if: success()
  #       run: make build-ubuntu-win32-py38
  #
  # build-nvidia-py38:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :nvidia-py38
  #       if: success()
  #       run: make build-nvidia-py38
  #
  # build-nvidia-win32-py38:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :nvidia-win32-py38
  #       if: success()
  #       run: make build-nvidia-win32-py38


  # Development branch
  build-ubuntu-devel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :ubuntu-devel
        if: success()
        run: make build-ubuntu-devel

  build-ubuntu-devel-win32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :ubuntu-devel-win32
        if: success()
        run: make build-ubuntu-devel-win32

  # build-nvidia-devel:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :nvidia-devel
  #       if: success()
  #       run: make build-nvidia-devel
  #
  # build-nvidia-devel-win32:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :nvidia-devel-win32
  #       if: success()
  #       run: make build-nvidia-devel-win32


  build-ubuntu-devel-py38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :ubuntu-devel-py38
        if: success()
        run: make build-ubuntu-devel-py38

  build-ubuntu-devel-win32-py38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :ubuntu-devel-win32-py38
        if: success()
        run: make build-ubuntu-devel-win32-py38

  # build-nvidia-devel-py38:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :nvidia-devel-py38
  #       if: success()
  #       run: make build-nvidia-devel-py38
  #
  # build-nvidia-devel-win32-py38:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :nvidia-devel-win32-py38
  #       if: success()
  #       run: make build-nvidia-devel-win32-py38
