name: Push to Docker registry

on:
  push:
    branches:    
      - master

jobs:
  deploy-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :latest
        if: success()
        run: make build

      - name: Deploy :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:latest

  deploy-nvidia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :nvidia
        if: success()
        run: make build-nvidia

      - name: Deploy :nvidia
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:nvidia
