name: Push to Docker registry

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  # Stable branch
  # deploy-latest:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :latest
  #       if: success()
  #       run: make build
  #
  #     - name: Deploy :latest
  #       if: success()
  #       uses: actions-hub/docker@master
  #       with:
  #         args: push aoirint/wine:latest
  #
  # deploy-ubuntu:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :ubuntu
  #       if: success()
  #       run: make build-ubuntu
  #
  #     - name: Deploy :ubuntu
  #       if: success()
  #       uses: actions-hub/docker@master
  #       with:
  #         args: push aoirint/wine:ubuntu
  #
  # deploy-ubuntu-win32:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :ubuntu-win32
  #       if: success()
  #       run: make build-ubuntu-win32
  #
  #     - name: Deploy :ubuntu-win32
  #       if: success()
  #       uses: actions-hub/docker@master
  #       with:
  #         args: push aoirint/wine:ubuntu-win32
  #
  # deploy-nvidia:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :nvidia
  #       if: success()
  #       run: make build-nvidia
  #
  #     - name: Deploy :nvidia
  #       if: success()
  #       uses: actions-hub/docker@master
  #       with:
  #         args: push aoirint/wine:nvidia
  #
  # deploy-nvidia-win32:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :nvidia-win32
  #       if: success()
  #       run: make build-nvidia-win32
  #
  #     - name: Deploy :nvidia-win32
  #       if: success()
  #       uses: actions-hub/docker@master
  #       with:
  #         args: push aoirint/wine:nvidia-win32
  #
  #
  # deploy-ubuntu-py38:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :ubuntu-py38
  #       if: success()
  #       run: make build-ubuntu-py38
  #
  #     - name: Deploy :ubuntu-py38
  #       if: success()
  #       uses: actions-hub/docker@master
  #       with:
  #         args: push aoirint/wine:ubuntu-py38
  #
  # deploy-ubuntu-win32-py38:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :ubuntu-win32-py38
  #       if: success()
  #       run: make build-ubuntu-win32-py38
  #
  #     - name: Deploy :ubuntu-win32-py38
  #       if: success()
  #       uses: actions-hub/docker@master
  #       with:
  #         args: push aoirint/wine:ubuntu-win32-py38
  #
  # deploy-nvidia-py38:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :nvidia-py38
  #       if: success()
  #       run: make build-nvidia-py38
  #
  #     - name: Deploy :nvidia-py38
  #       if: success()
  #       uses: actions-hub/docker@master
  #       with:
  #         args: push aoirint/wine:nvidia-py38
  #
  # deploy-nvidia-win32-py38:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Login to docker hub
  #       uses: actions-hub/docker/login@master
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         DOCKER_REGISTRY_URL: docker.io
  #
  #     - name: Build :nvidia-win32-py38
  #       if: success()
  #       run: make build-nvidia-win32-py38
  #
  #     - name: Deploy :nvidia-win32-py38
  #       if: success()
  #       uses: actions-hub/docker@master
  #       with:
  #         args: push aoirint/wine:nvidia-win32-py38

  # Development branch
  deploy-ubuntu-devel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :ubuntu-devel
        if: success()
        run: make build-ubuntu-devel

      - name: Deploy :ubuntu-devel
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:ubuntu-devel

      - name: Tag :ubuntu-devel as :ubuntu-devel-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: image tag aoirint/wine:ubuntu-devel aoirint/wine:ubuntu-devel-${{ github.event.release.tag_name }}

      - name: Deploy :ubuntu-devel-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:ubuntu-devel-${{ github.event.release.tag_name }}

  deploy-ubuntu-devel-win32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :ubuntu-devel-win32
        if: success()
        run: make build-ubuntu-devel-win32

      - name: Deploy :ubuntu-devel-win32
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:ubuntu-devel-win32

      - name: Tag :ubuntu-devel-win32 as :ubuntu-devel-win32-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: image tag aoirint/wine:ubuntu-devel-win32 aoirint/wine:ubuntu-devel-win32-${{ github.event.release.tag_name }}

      - name: Deploy :ubuntu-devel-win32-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:ubuntu-devel-win32-${{ github.event.release.tag_name }}

  deploy-nvidia-devel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :nvidia-devel
        if: success()
        run: make build-nvidia-devel

      - name: Deploy :nvidia-devel
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:nvidia-devel

      - name: Tag :nvidia-devel as :nvidia-devel-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: image tag aoirint/wine:nvidia-devel aoirint/wine:nvidia-devel-${{ github.event.release.tag_name }}

      - name: Deploy :nvidia-devel-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:nvidia-devel-${{ github.event.release.tag_name }}

  deploy-nvidia-devel-win32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :nvidia-devel-win32
        if: success()
        run: make build-nvidia-devel-win32

      - name: Deploy :nvidia-devel-win32
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:nvidia-devel-win32

      - name: Tag :nvidia-devel as :nvidia-devel-win32-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: image tag aoirint/wine:nvidia-devel-win32 aoirint/wine:nvidia-devel-win32-${{ github.event.release.tag_name }}

      - name: Deploy :nvidia-devel-win32-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:nvidia-devel-win32-${{ github.event.release.tag_name }}


  deploy-ubuntu-devel-py38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :ubuntu-devel-py38
        if: success()
        run: make build-ubuntu-devel-py38

      - name: Deploy :ubuntu-devel-py38
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:ubuntu-devel-py38

      - name: Tag :nvidia-devel as :ubuntu-devel-py38-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: image tag aoirint/wine:ubuntu-devel-py38 aoirint/wine:ubuntu-devel-py38-${{ github.event.release.tag_name }}

      - name: Deploy :ubuntu-devel-py38-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:ubuntu-devel-py38-${{ github.event.release.tag_name }}

  deploy-ubuntu-devel-win32-py38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :ubuntu-devel-win32-py38
        if: success()
        run: make build-ubuntu-devel-win32-py38

      - name: Deploy :ubuntu-devel-win32-py38
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:ubuntu-devel-win32-py38

      - name: Tag :ubuntu-devel-win32-py38 as :ubuntu-devel-win32-py38-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: image tag aoirint/wine:ubuntu-devel-win32-py38 aoirint/wine:ubuntu-devel-win32-py38-${{ github.event.release.tag_name }}

      - name: Deploy :ubuntu-devel-win32-py38-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:ubuntu-devel-win32-py38-${{ github.event.release.tag_name }}

  deploy-nvidia-devel-py38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :nvidia-devel-py38
        if: success()
        run: make build-nvidia-devel-py38

      - name: Deploy :nvidia-devel-py38
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:nvidia-devel-py38

      - name: Tag :nvidia-devel-py38 as :nvidia-devel-py38-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: image tag aoirint/wine:nvidia-devel-py38 aoirint/wine:nvidia-devel-py38-${{ github.event.release.tag_name }}

      - name: Deploy :nvidia-devel-py38-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:nvidia-devel-py38-${{ github.event.release.tag_name }}

  deploy-nvidia-devel-win32-py38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :nvidia-devel-win32-py38
        if: success()
        run: make build-nvidia-devel-win32-py38

      - name: Deploy :nvidia-devel-win32-py38
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:nvidia-devel-win32-py38

      - name: Tag :nvidia-devel-win32-py38 as :nvidia-devel-win32-py38-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: image tag aoirint/wine:nvidia-devel-win32-py38 aoirint/wine:nvidia-devel-win32-py38-${{ github.event.release.tag_name }}

      - name: Deploy :nvidia-devel-win32-py38-${{ github.event.release.tag_name }}
        if: success() && ${{ github.event.release.tag_name != '' }}
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:nvidia-devel-win32-py38-${{ github.event.release.tag_name }}
