name: Push to Docker registry

on:
  push:
    branches:
      - master

jobs:
  # Stable branch
  deploy-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :latest
        if: success()
        run: make build

      - name: Deploy :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:latest

  deploy-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :ubuntu
        if: success()
        run: make build-ubuntu

      - name: Deploy :ubuntu
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:ubuntu

  deploy-nvidia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :nvidia
        if: success()
        run: make build-nvidia

      - name: Deploy :nvidia
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:nvidia


  deploy-ubuntu-py38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :ubuntu-py38
        if: success()
        run: make build-ubuntu-py38

      - name: Deploy :ubuntu-py38
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:ubuntu-py38

  deploy-nvidia-py38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :nvidia-py38
        if: success()
        run: make build-nvidia-py38

      - name: Deploy :nvidia-py38
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:nvidia-py38

  # Development branch
  deploy-ubuntu-devel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :ubuntu-devel
        if: success()
        run: make build-ubuntu-devel

      - name: Deploy :ubuntu-devel
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:ubuntu-devel

  deploy-nvidia-devel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :nvidia-devel
        if: success()
        run: make build-nvidia-devel

      - name: Deploy :nvidia
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:nvidia-devel


  deploy-ubuntu-devel-py38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :ubuntu-py38
        if: success()
        run: make build-ubuntu-devel-py38

      - name: Deploy :ubuntu-py38
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:ubuntu-devel-py38

  deploy-nvidia-devel-py38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :nvidia-devel-py38
        if: success()
        run: make build-nvidia-devel-py38

      - name: Deploy :nvidia-py38
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/wine:nvidia-devel-py38
